# Base image: ubuntu:22.04
FROM ubuntu:22.04

# ARGs
# https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG TARGETPLATFORM=linux/amd64,linux/arm64
ARG DEBIAN_FRONTEND=noninteractive

# neo4j 2025.08.0 installation (match GDS v2.21.0) and some cleanup
RUN apt-get update && \
    apt-get install -y wget gnupg software-properties-common && \
    wget -O - https://debian.neo4j.com/neotechnology.gpg.key | apt-key add - && \
    echo 'deb https://debian.neo4j.com stable latest' > /etc/apt/sources.list.d/neo4j.list && \
    add-apt-repository universe && \
    apt-get update && \
    apt-get install -y nano unzip neo4j=1:2025.08.0 python3-pip && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# TODO: Complete the Dockerfile
# Step 1:
WORKDIR /cse511
# Step 2:
RUN wget -q https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet \
-O /cse511/yellow_tripdata_2022-03.parquet
# Step 3:
COPY ./data_loader.py /cse511/data_loader.py
# Step 4:
RUN apt-get update && apt-get install -y openjdk-21-jdk && rm -rf /var/lib/apt/lists/*
ARG TARGETARCH
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-$TARGETARCH
ENV PATH="$JAVA_HOME/bin:$PATH"
# Step 5:
RUN python3 -m pip install --no-cache-dir --upgrade pip && python3 -m pip install --no-cache-dir neo4j pandas pyarrow
# Step 6:
RUN mkdir -p /var/lib/neo4j/plugins && \
wget -q https://github.com/neo4j/graph-data-science/releases/download/2.21.0/neo4j-graph-data-science-2.21.0.jar \
-O /var/lib/neo4j/plugins/neo4j-graph-data-science-2.21.0.jar
# Step 7:
RUN set -eux; conf="/etc/neo4j/neo4j.conf"; \
    for setting in \
      "server.default_listen_address=0.0.0.0" \
      "server.directories.plugins=/var/lib/neo4j/plugins" \
      "dbms.security.procedures.unrestricted=gds.*,apoc.*" \
      "dbms.security.procedures.allowlist=gds.*,apoc.*" \
    ; do name=${setting%%=*}; sed -i "/^${name}=*/d" "$conf"; echo "$setting" >> "$conf"; done
# Step 8:
RUN neo4j-admin dbms set-initial-password graphprocessing

# Run the data loader script
RUN chmod +x /cse511/data_loader.py && \
    neo4j start && \
    python3 data_loader.py && \
    neo4j stop

# Expose neo4j ports
EXPOSE 7474 7687

# Start neo4j service and show the logs on container run
CMD ["/bin/bash", "-c", "neo4j start && tail -f /dev/null"]
