neo4j:
  name: neo4j
  edition: "enterprise"
  password: "processingpipeline"
  acceptLicenseAgreement: "yes"

  plugins:
    - "apoc"
    - "graph-data-science"

  resources:
    cpu: "4"
    memory: "2Gi"

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 5Gi

config:
  dbms.memory.heap.initial_size: "1G"
  dbms.memory.heap.max_size: "1G"
  dbms.memory.pagecache.size: "512M"
  dbms.security.procedures.unrestricted: "gds., apoc."
  dbms.security.procedures.allowlist: "gds., apoc."
